name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build x86
      run: msbuild /m /p:Configuration=Release /p:Platform=x86 AutorunReloadFonts.sln

    - name: Build x64
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 AutorunReloadFonts.sln

    - name: Prepare Release Folder
      shell: pwsh
      run: |
        mkdir release_dist
        $dll32 = Get-ChildItem -Path . -Filter "AutorunReloadFonts.dll" -Recurse | Where-Object { $_.FullName -like "*Release*" -and $_.FullName -notlike "*x64*" } | Select-Object -First 1
        $dll64 = Get-ChildItem -Path . -Filter "AutorunReloadFonts.dll" -Recurse | Where-Object { $_.FullName -like "*Release*" -and $_.FullName -like "*x64*" } | Select-Object -First 1
        
        if ($dll32) { Copy-Item $dll32.FullName -Destination "release_dist\AutorunReloadFonts.dll" }
        else { throw "32-bit DLL not found!" }
        
        if ($dll64) { Copy-Item $dll64.FullName -Destination "release_dist\AutorunReloadFonts.dll64" }
        else { throw "64-bit DLL not found!" }

    - name: Create Zip
      shell: pwsh
      run: Compress-Archive -Path release_dist\* -DestinationPath AutorunReloadFonts.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: AutorunReloadFonts.zip
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
